### ISSUE TITLE
Prompt broken with node 5.6 and 5.7 on win >= 8

### ISSUE THREAD

**Issue by Skywalker13** [Xcraft-Inc/shellcraft.js#12]
See https://github.com/nodejs/node/issues/5384

**Comment by egoroof** [comment]
Does it work with node 5.6.0?

**Comment by Skywalker13** [comment]
It works better than 5.7 but the bug https://github.com/nodejs/node/issues/2996 exists (the first event is not triggered).

**Comment by Skywalker13** [comment]
Sorry, it's not better, 5.6 and 5.7 has the same problem.

**Comment by lawkai** [comment]
Same problem with Node 5.8.0 with Windows 10 x64

**Comment by Skywalker13** [comment]
Yes, the issue is still open https://github.com/nodejs/node/issues/5384

**Comment by Skywalker13** [comment]
Fixed since node v6.2
